/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { TwitchAPIClient } from "./TwitchAPIClient";

export { ApiError } from "./core/ApiError";
export { BaseHttpRequest } from "./core/BaseHttpRequest";
export { CancelError, CancelablePromise } from "./core/CancelablePromise";
export { OpenAPI } from "./core/OpenAPI";
export type { OpenAPIConfig } from "./core/OpenAPI";

export type { AgeRating } from "./models/AgeRating";
export type { AgeRatingCategoryEnums } from "./models/AgeRatingCategoryEnums";
export type { AgeRatingContentDescription } from "./models/AgeRatingContentDescription";
export type { AgeRatingContentDescriptionCategoryEnums } from "./models/AgeRatingContentDescriptionCategoryEnums";
export type { AgeRatingEnums } from "./models/AgeRatingEnums";
export type { AlternativeNames } from "./models/AlternativeNames";
export type { Artwork } from "./models/Artwork";
export type { ChangeDateCategoryEnum } from "./models/ChangeDateCategoryEnum";
export type { Character } from "./models/Character";
export type { CharacterGenderEnum } from "./models/CharacterGenderEnum";
export type { CharacterMugShot } from "./models/CharacterMugShot";
export type { CharacterSpeciesEnum } from "./models/CharacterSpeciesEnum";
export type { Collection } from "./models/Collection";
export type { CollectionMembership } from "./models/CollectionMembership";
export type { CollectionMembershipType } from "./models/CollectionMembershipType";
export type { CollectionRelation } from "./models/CollectionRelation";
export type { CollectionRelationType } from "./models/CollectionRelationType";
export type { CollectionType } from "./models/CollectionType";
export type { Company } from "./models/Company";
export type { CompanyLogo } from "./models/CompanyLogo";
export type { CompanyWebsite } from "./models/CompanyWebsite";
export type { CompanyWebsiteEnums } from "./models/CompanyWebsiteEnums";
export type { Cover } from "./models/Cover";
export type { Event } from "./models/Event";
export type { EventLogo } from "./models/EventLogo";
export type { EventNetwork } from "./models/EventNetwork";
export type { ExternalGame } from "./models/ExternalGame";
export type { ExternalGameCategoryEnums } from "./models/ExternalGameCategoryEnums";
export type { ExternalGameMediaEnums } from "./models/ExternalGameMediaEnums";
export type { Franchise } from "./models/Franchise";
export type { GameCategoryEnums } from "./models/GameCategoryEnums";
export type { GameEngine } from "./models/GameEngine";
export type { GameEngineLogo } from "./models/GameEngineLogo";
export type { GameLocalization } from "./models/GameLocalization";
export type { GameMode } from "./models/GameMode";
export type { GameStatusEnums } from "./models/GameStatusEnums";
export type { GameTimeToBeat } from "./models/GameTimeToBeat";
export type { GameVersion } from "./models/GameVersion";
export type { GameVersionFeatureCategoryEnums } from "./models/GameVersionFeatureCategoryEnums";
export type { GameVersionFeatureValue } from "./models/GameVersionFeatureValue";
export type { GameVersionFeatures } from "./models/GameVersionFeatures";
export type { GameVersionIncludedFeatureEnums } from "./models/GameVersionIncludedFeatureEnums";
export type { GameVideo } from "./models/GameVideo";
export type { Games } from "./models/Games";
export type { Genre } from "./models/Genre";
export type { InvolvedCompany } from "./models/InvolvedCompany";
export type { Keyword } from "./models/Keyword";
export type { Language } from "./models/Language";
export type { LanguageSupport } from "./models/LanguageSupport";
export type { LanguageSupportType } from "./models/LanguageSupportType";
export type { MultiplayerMode } from "./models/MultiplayerMode";
export type { NetworkType } from "./models/NetworkType";
export type { Platform } from "./models/Platform";
export type { PlatformCategoryEnums } from "./models/PlatformCategoryEnums";
export type { PlatformFamily } from "./models/PlatformFamily";
export type { PlatformLogo } from "./models/PlatformLogo";
export type { PlatformVersion } from "./models/PlatformVersion";
export type { PlatformVersionCompany } from "./models/PlatformVersionCompany";
export type { PlatformVersionReleaseDate } from "./models/PlatformVersionReleaseDate";
export type { PlatformVersionReleaseDateEnums } from "./models/PlatformVersionReleaseDateEnums";
export type { PlatformVersionReleaseDateRegionEnum } from "./models/PlatformVersionReleaseDateRegionEnum";
export type { PlatformWebsite } from "./models/PlatformWebsite";
export type { PlatformWebsiteCategoryEnums } from "./models/PlatformWebsiteCategoryEnums";
export type { PlayerPerspective } from "./models/PlayerPerspective";
export type { PopularityPrimatives } from "./models/PopularityPrimatives";
export type { PopularityPrimitiveEnum } from "./models/PopularityPrimitiveEnum";
export type { PopularityTypeEnum } from "./models/PopularityTypeEnum";
export type { PopularityTypes } from "./models/PopularityTypes";
export type { Region } from "./models/Region";
export type { ReleaseDate } from "./models/ReleaseDate";
export type { ReleaseDateCategoryEnums } from "./models/ReleaseDateCategoryEnums";
export type { ReleaseDateRegionEnum } from "./models/ReleaseDateRegionEnum";
export type { ReleaseDateStatus } from "./models/ReleaseDateStatus";
export type { Screenshot } from "./models/Screenshot";
export type { Search } from "./models/Search";
export type { StartDateCategoryEnum } from "./models/StartDateCategoryEnum";
export type { Theme } from "./models/Theme";
export type { Website } from "./models/Website";
export type { WebsiteCategoryEnums } from "./models/WebsiteCategoryEnums";

export { EndpointsService } from "./services/EndpointsService";
