name: Main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Development
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
      - run: yarn install
      - id: "auth"
        uses: "google-github-actions/auth@v2.1.13"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      - run: gcloud auth configure-docker gcr.io
      - uses: docker/setup-buildx-action@v3.11.1
      - uses: pulumi/actions@v3
        with:
          cloud-url: gs://bos-pulumi-state-bucket
          command: up
          refresh: true
          stack-name: dev
          work-dir: infrastructure/app
