name: nuxt-gcp
on:
  push:
    branches:
      - nuxt-gcp
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version-file: .nvmrc
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      - run: yarn install
      - uses: pulumi/actions@v3
        with:
          cloud-url: gs://bos-pulumi-state-bucket
          command: up
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          stack-name: production
          work-dir: infrastructure
