name: Version Tag
on:
  push:
    tags:
      - v[12].[0-9]+.[0-9]+
jobs:
  migrate:
    name: Migrate Production
    runs-on: ubuntu-24.04
    env:
      BOS_DATABASE_URL: ${{ secrets.BOS_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4.3.0
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
      - id: "cloudsql-proxy"
        uses: mattes/gce-cloudsql-proxy-action@v1.0.1
        with:
          creds: ${{ secrets.GCP_CREDENTIAL }}
          instance: basement-of-stinkology:us-central1:bos-postgres-instance-a04d6d6
      - run: pnpm install
      - run: pnpm prisma migrate deploy
  deploy:
    name: Deploy Production
    runs-on: ubuntu-24.04
    needs: migrate
    steps:
      - uses: actions/checkout@v4.3.0
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
      - id: "auth"
        uses: "google-github-actions/auth@v2.1.13"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      - run: gcloud auth configure-docker gcr.io
      - uses: docker/setup-buildx-action@v3.11.1
      - uses: pulumi/actions@v5.5.1
        with:
          cloud-url: gs://bos-pulumi-state-bucket
          command: up
          refresh: true
          stack-name: production
          work-dir: infrastructure/app
